@startuml sequence
actor Customer
actor Vendor
actor "Vending Machine" as VM
actor "Inventory Database" as DB
actor "Payment Gateway" as PG

Customer -> VM: Approach
Customer -> VM: Tap Card/QR code
activate VM
VM -> PG: Is Card/QR Recognized?
activate PG
alt Card Recognized
    PG --> VM: Card/QR Validated
    VM -> VM: Unlock Door
    VM -> VM: Display "Welcome"
    VM -> VM: Display "Validating card/QR"
    alt Valid Card/QR
        VM -> VM: Display "Door opened... Choose your items"
        Customer -> VM: Select Items
        loop Select Items
            Customer -> VM: Selects Item
            VM -> VM: Display "You picked up A item, updates in cart"
            alt Item Placed Back Incorrectly
                VM -> VM: Display "Error! : Please place the item back in its place to continue"
            end
        end
        
        VM -> VM: Display "You sure you wanna continue to payment?"
        Customer -> VM: Close Door
        VM -> VM: Check Inventory
        alt Inventory Not Low
            VM -> PG: Charge Card/Wallet
            PG --> VM: Card/Wallet Charged for Items Taken
            VM -> VM: Display "Transaction Complete"
            PG --> Customer: Transaction Complete
        else Inventory Low
            VM -> Vendor: Alert for Restocking
            Vendor -> Vendor: Check Inventory Report
            Vendor -> Vendor: Restock Items
            Vendor -> DB: Update Product Database
        end
    else Invalid Card
        VM -> VM: Display "Not found, door not open... Try again or with a different card/QR"
    end
else Card/QR Not Recognized
    VM -> VM: Display "Invalid Card/QR"
end
@enduml