@startuml useCase
left to right direction

actor Customer
actor Vendor
actor "Vending Machine" as VM
actor "Inventory Database" as DB
actor "Payment Gateway" as PG

rectangle "Use Cases" {
    Customer --> (Approach Vending Machine)
    Customer --> (Tap Card/QR code)
    Customer --> (Select Items)
    Customer --> (Close Door)
    Customer --> (Transaction Complete)

    Vendor --> (Receive Restocking Alert)
    Vendor --> (Check Inventory Report)
    Vendor --> (Restock Items)
    
    VM --> (Unlock Door)
    VM --> (Display Welcome Message)
    VM --> (Display Validating card/QR Message)
    VM --> (Display Door opened... Choose your items Message)
    VM --> (Display Payment Confirmation Message)
    VM --> (Display Transaction Completion Message)
    VM --> (Display Invalid Card/QR Message)
}

DB --> VM: Update Inventory
PG --> VM: Process Payment
@enduml