@startuml activity

start
:Customer approaches vending machine;
:Customer taps card/QR code;
if (Is card/QR recognized?) then (yes)
  :Display "Validating card/QR";
  if (Card/QR validated?) then (yes)
    :Unlock door;
    :Display "Door opened... Choose your items";
    repeat
      :Select item;
      :Update cart;
    repeat while (More items?);
    :Display "You sure you wanna continue to payment?";
    :Close door;
    :Check inventory;
    if (Inventory low?) then (yes)
      :Alert for restocking;
      :Check inventory report;
      :Restock items;
      :Update product database;
    else (Inventory sufficient)
      :Charge card/Wallet;
      if (Payment successful?) then (yes)
        :Transaction complete;
        :Display "Transaction complete";
        :Send transaction complete message;
      else (Payment declined)
        :Display "Transaction declined, retry payment";
      endif
    endif
  else (Invalid card/QR)
    :Display "Not found, door not open... Try again or with a different card/QR";
  endif
else (Card/QR not recognized)
  :Display "Invalid card/QR";
endif
stop

@enduml
