@startuml domain
package "Vending Machine System" {
    class Customer
    class Vendor
    class VendingMachine
    class InventoryDatabase
    class PaymentGateway
    class Item
}

Customer -- VendingMachine : Uses
Vendor -- VendingMachine : Uses
VendingMachine --> InventoryDatabase : Uses
VendingMachine --> PaymentGateway : Uses
InventoryDatabase --> Item : Contains
@enduml